import { Octokit } from "@octokit/rest";
import { GitHubConfig, SecurityControl } from "../types";

export const pushToGitHub = async (
  config: GitHubConfig, 
  serviceName: string, 
  controls: SecurityControl[]
) => {
  const octokit = new Octokit({ auth: config.token });
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const branchName = `security-controls/${serviceName.replace(/\s+/g, '-').toLowerCase()}-${timestamp}`;
  const fileName = `controls/${serviceName.replace(/\s+/g, '_')}_controls.md`;

  try {
    // 1. Get Reference to base branch (usually main)
    const { data: refData } = await octokit.git.getRef({
      owner: config.owner,
      repo: config.repo,
      ref: `heads/${config.branchBase}`,
    });

    const baseSha = refData.object.sha;

    // 2. Create new Branch
    await octokit.git.createRef({
      owner: config.owner,
      repo: config.repo,
      ref: `refs/heads/${branchName}`,
      sha: baseSha,
    });

    // 3. Create Markdown Content
    const mdContent = `# Security Controls: ${serviceName}

| ID | Name | Description | Plane | Mapping |
|----|------|-------------|-------|---------|
${controls.map(c => `| ${c.controlId} | ${c.controlName} | ${c.controlDescription} | ${c.plane} | ${c.mapping} |`).join('\n')}

*Generated by CloudGuard Gen*
`;

    const contentEncoded = btoa(mdContent);

    // 4. Create File
    await octokit.repos.createOrUpdateFileContents({
      owner: config.owner,
      repo: config.repo,
      path: fileName,
      message: `Add security controls for ${serviceName}`,
      content: contentEncoded,
      branch: branchName,
    });

    // 5. Create Pull Request
    const { data: prData } = await octokit.pulls.create({
      owner: config.owner,
      repo: config.repo,
      title: `Security Controls: ${serviceName}`,
      head: branchName,
      base: config.branchBase,
      body: `Automated PR containing security controls for **${serviceName}**.\n\nPlease review against organizational standards.`,
    });

    // 6. Request Reviewers
    if (config.reviewers.trim()) {
      const reviewers = config.reviewers.split(',').map(r => r.trim()).filter(r => r.length > 0);
      if (reviewers.length > 0) {
        await octokit.pulls.requestReviewers({
          owner: config.owner,
          repo: config.repo,
          pull_number: prData.number,
          reviewers: reviewers,
        });
      }
    }

    return prData.html_url;

  } catch (error) {
    console.error("GitHub Operation failed:", error);
    throw error;
  }
};